language: objective-c
podfile: Example/Podfile

before_install:
- gem install activesupport -v 4.2.6 # Need this because of travis
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/SCConfiguration.xcworkspace -scheme SCConfiguration-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
